server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.6.61.31;database=pts
    username: gx-mes
    password: x0h16p
#    url: jdbc:sqlserver://10.6.61.75;database=filter_db_test
#    username: SA
#    password: Csk@513434
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    # 地址
    host: 10.6.61.75
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
cache-expire:
  ttl:
    #秒
    deviceInfoList: -1
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ht.shaixuan.entity
# MyBatis SQL打印
logging:
  level:
    com.ht.screening.mapper: debug
#log.home: /Users/chengsukai/Desktop/workspace/work/ht/end/fiber-platform/screening/src/main/java/com/ht/screening/log
#log.home: D:/workspace/logs