server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://10.6.100.236;database=pts
    #    username: admin
    #    password: dev_2019
    url: jdbc:sqlserver://10.6.61.31;database=pts
    username: gx-mes
    password: x0h16p
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ht.shaixuan.entity
cache-config:
  specs:
    deviceInfo:
      # 过期时间
      expire-time: 2678400
      # 缓存最大数量
      max-size: 200
    admin:
      expire-time: 20
      max-size: 200
# MyBatis SQL打印
logging:
  level:
    com.ht.screening.mapper: debug